# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  vms = {
    :vm1 => "192.168.33.10",
    :vm2 => "192.168.33.20",
    :vm3 => "192.168.33.30",
    :vm4 => "192.168.33.40",
    :vm5 => "192.168.33.50",
  }

  vms.keys.each do |vm|

    config.vm.define "#{vm}" do |box|
      box.vm.hostname = "#{vm}"
      box.vm.box = "ubuntu/xenial64"
      box.vm.network "private_network", ip: vms[vm]

      box.vm.provision "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "bootstrap.yaml"
      end
    end
  end
end
